name: Greetings
on: [pull_request, issues]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Hello!
          
          Welcome to the Bitcask project! Someone will respond to your issue pretty quickly,
          the author is pretty responsive ðŸ˜€ In the meantime; please make sure you have read
          the [Contributing](https://github.com/prologic/bitcask/blob/master/CONTRIBUTING.md)
          and [Code of Conduct](https://github.com/prologic/bitcask/blob/master/CODE_OF_CONDUCT.md)
          documents.
          
          if possible please also make sure your Bug Report or Feature Request is clearly defined
          with either examples or a reprodicible case (_if a bug_).
          
          Thank you ðŸ˜ƒ
        pr-message: |-
          Hello!
          
          Welcome to the Bitcask project!
          
          Thank you for your Pull Request and Contribution! We highly value all contributions to this Project!
          Your Pull Request will be reviewed shortly! The author is pretty responsive ðŸ˜€
           In the meantime; please make sure you have read
          the [Contributing](https://github.com/prologic/bitcask/blob/master/CONTRIBUTING.md)
          and [Code of Conduct](https://github.com/prologic/bitcask/blob/master/CODE_OF_CONDUCT.md)
          documents.
          
          Please also ensure that your PR passes all the CI/CD tests -- They will appear in your PR
          towards the bottom just above the comment box.
          
          Also in addition, if you haven't already; please ammend your PR by modifying the
          [AUTHORS](https://github.com/prologic/bitcask/blob/master/AUTHORS) file and adding
          yourself to it! We like to recognize and peserve in Git history all contributors!
          
          Thank you ðŸ˜ƒ
